set(MONGOCXX_LIB "${CMAKE_CURRENT_SOURCE_DIR}/external/lib/libmongocxx.so" "${CMAKE_CURRENT_SOURCE_DIR}/external/lib/libbsoncxx.so")
set(MONGOCXX_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/external/include)

ExternalProject_Add(mongocxx
        PREFIX mongocxx
        GIT_REPOSITORY https://github.com/mongodb/mongo-cxx-driver.git
        GIT_TAG releases/v3.2
        EXCLUDE_FROM_ALL 0
#        SOURCE_SUBDIR Release
        EXCLUDE_FROM_ALL 0
#        CMAKE_CACHE_ARGS "-DCPPREST_EXCLUDE_WEBSOCKETS=OFF"
#        CMAKE_CACHE_ARGS "-DBUILD_SAMPLES:BOOL=OFF"
#        CMAKE_CACHE_ARGS "-DBUILD_TESTS:BOOL=OFF"
        CMAKE_CACHE_ARGS "-DOPENSSL_CRYPTO_LIBRARY:FILEPATH=${OPENSSL_CRYPTO_LIBRARY}"
        CMAKE_CACHE_ARGS "-DOPENSSL_INCLUDE_DIR:PATH=${OPENSSL_INCLUDE_DIR}"
        CMAKE_CACHE_ARGS "-DOPENSSL_SSL_LIBRARY:FILEPATH=${OPENSSL_SSL_LIBRARY}"
#        CMAKE_CACHE_ARGS "-DBUILD_SHARED_LIBS:BOOL=OFF"
#        CMAKE_CACHE_ARGS "-DCMAKE_CXX_FLAGS:STRING=-fPIC -Wno-error=format-truncation="
        CMAKE_CACHE_ARGS "-DCMAKE_BUILD_TYPE:STRIING=Release"
        CMAKE_CACHE_ARGS "-DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_CURRENT_SOURCE_DIR}/external"
        CMAKE_CACHE_ARGS "-DBSONCXX_POLY_USE_MNMLSTC:BOOL=OFF"
        CMAKE_CACHE_ARGS "-DBSONCXX_POLY_USE_BOOST:BOOL=OFF"
        CMAKE_CACHE_ARGS "-DBSONCXX_POLY_USE_STD_EXPERIMENTAL:BOOL=OFF"
        CMAKE_CACHE_ARGS "-DBSONCXX_POLY_USE_STD:BOOL=ON"
        CMAKE_CACHE_ARGS "-DBOOST_ROOT:PATH=${BOOST_ROOT}"
        CMAKE_CACHE_ARGS "-DCMAKE_CXX_FLAGS:STRING=-std=c++17"
        CMAKE_CACHE_ARGS "-DCMAKE_CXX_STANDARD:STRING=17"

        #        CMAKE_CACHE_ARGS "-DBSON_INCLUDE_DIRS=${CMAKE_CURRENT_SOURCE_DIR}/external/include/bsoncxx/v_noabi"
#        BSON_INCLUDE_DIRS
        BUILD_BYPRODUCTS ${MONGOCXX_LIB}

        )

# ubuntu 18.04 depends on:
# libbson-dev libmongoc-dev